[package]
name = "website"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
topcoat = { version = "0.10.0", features = ["tailwind"] }
topcoat-asset = { version = "0.10.0", features = ["bundler"] }

[build-dependencies]
topcoat = { version = "0.10.0", default-features = false, features = ["tailwind"] }
